version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '08:00'
    timezone: America/Winnipeg
  open-pull-requests-limit: 3
  assignees:
  - michaelabon
