version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '08:00'
    timezone: America/Vancouver
  open-pull-requests-limit: 10
  assignees:
  - michaelabon
