AllCops:
  DisplayCopNames:
    Enabled: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'bucket/**/*'
    - 'lib/tasks/**/*.rake'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3


# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: true

# Configuration parameters: AlignWith, SupportedStyles.
Lint/DefEndAlignment:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 20

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 8

# Configuration parameters: AllowURI.
Metrics/LineLength:
  Max: 80

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 44

Metrics/PerceivedComplexity:
  Max: 10

Rails:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/Validation:
  Enabled: true

Style/AccessorMethodName:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: true

Style/Documentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/DotPosition:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: true

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodName:
  Enabled: true

Style/PerlBackrefs:
  Enabled: false

Style/Tab:
  Enabled: true
