inherit_from: .rubocop_todo.yml

require: rubocop-rspec
Rails:
  Enabled: true
AllCops:
  DisplayCopNames:
    Enabled: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'bucket/**/*'
    - 'lib/tasks/**/*.rake'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4


# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: true

# Configuration parameters: AlignWith, SupportedStyles.
Layout/DefEndAlignment:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 8

# Configuration parameters: AllowURI.
Metrics/LineLength:
  Max: 80

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 44

Metrics/PerceivedComplexity:
  Max: 10

Rails:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/Validation:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: true

Style/Documentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Layout/DotPosition:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: true

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Naming/MethodName:
  Enabled: true

Style/PerlBackrefs:
  Enabled: false

Layout/Tab:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - and
    - but
