# A response generated by a processor,
# before postprocessing.
#
# This intermediate object carries
# both the response text and metadata (trigger, verb, user)
# that postprocessors need
# to format the final output correctly.
# For example,
# the verb determines whether the response becomes
# an action,
# a direct reply,
# or an "X is Y" statement.
class MessageResponse
  attr_accessor :text, :trigger, :user_name, :verb

  def initialize(text: nil, trigger: nil, user_name: nil, verb: nil)
    @text = text
    @trigger = trigger
    @user_name = user_name
    @verb = verb
  end
end
